# Change these first
owner: jeircul # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: joracul
    url: https://www.joracul.duckdns.org/
  - name: Nextcloud
    url: https://nextcloud.joracul.duckdns.org
  - name: PhotoPrism
    url: https://photoprism.joracul.duckdns.org
  - name: API Ethplorer
    url: https://api.ethplorer.io/getLastBlock?apiKey=freekey
  - name: API Ethplorer BSC
    url: https://api.binplorer.com/getLastBlock?apiKey=freekey
  - name: API CoinGecko
    url: https://api.coingecko.com/api/v3/ping
  - name: API Firi
    url: https://api.firi.com/time
    headers:
      - "Content-Type: application/json"
      - "miraiex-access-key: $FIRI_API"
  - name: API Solscan
    url: https://public-api.solscan.io/block/last?limit=10
    icon: https://solscan.io/static/media/solana-sol-logo.b612f1402147c92338bed5af1879b175.svg
    headers:
      - "Content-Type: application/json"
  - name: Upptime
    url: https://jeircul.github.io/upptime/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
