# Change these first
owner: jeircul # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Upptime
    url: https://jeircul.github.io/upptime/
  - name: joracul
    url: https://www.joracul.duckdns.org/
  - name: Nextcloud
    url: https://nextcloud.joracul.duckdns.org
  - name: PhotoPrism
    url: https://photoprism.joracul.duckdns.org
  - name: Ethplorer Ethereum Mainnet
    url: https://api.ethplorer.io/getLastBlock?apiKey=freekey
  - name: Ethplorer Binance Smart Chain
    url: https://api.binplorer.com/getLastBlock?apiKey=freekey

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  theme: dark
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/jeircul/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
